version: "3.1"

volumes:
  pg_selectel:

services:
  pg_db:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  backend_blog:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    command: npm run start
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
